### ISSUE TITLE
ValueError: 'AAAS' is not in list

### ISSUE THREAD

**Issue by mayurdoke6** [andreariba/DeepCycle#13]
Hello, 

I am getting the following error. Could you please help me with this issue?

(DeepCycle) mayurd@mayurdlaptop:~/Downloads/DeepCycle-main$ python DeepCycle.py   --input_adata my_results.h5ad   --gene_list go_annotation/GO_cell_cycle_annotation_human.txt   --base_gene MELK   --expression_threshold 0   --output_adata adata_newbeta_DeepCycle.h5ad
2023-03-02 15:59:24.865319: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-02 15:59:24.969386: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-02 15:59:24.969408: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-02 15:59:25.526120: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-02 15:59:25.526177: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-02 15:59:25.526185: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[Current working directory]: /home/mayurd/Downloads/DeepCycle-main
[TensorFlow version]: 2.11.0
[Loading anndata]: my_results.h5ad
[Loading genes]: go_annotation/GO_cell_cycle_annotation_human.txt
Traceback (most recent call last):
  File "/home/mayurd/Downloads/DeepCycle-main/DeepCycle.py", line 384, in <module>
    genes, np_data = generate_input(filtered_cell_cycle_genes, adata)
  File "/home/mayurd/Downloads/DeepCycle-main/DeepCycle.py", line 351, in generate_input
    n = gene_list.index(list_of_genes[0])
**ValueError: 'AAAS' is not in list**

**Comment by mauliknariya** [comment]
Hello,

I had a similar error. This is likely happening because the gene 'AAAS'
(the first entry in GO_cell_cycle_annotation_human.txt) was not profiled in
your scRNA data. I would take the intersection of the genes profiled in
your data and the genes in the cell cycle annotation file and create a
separate file, and use that  for your --gene_list.

I hope this helps

**Comment by JDBLab** [comment]
Hello, @mauliknariya Thank you so much for your immense help !!!
